---
# tasks file for wp-dependencies
- name: Intall reuired packages
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - mariadb-server
    - mariadb
    - php
    - php-mysql
    - MySQL-python
- name: Start mariadb
  service: name=mariadb state=started enabled=yes
#- name: Copy .my.cnf to nodes
#  copy: src=.my.cnf dest=/root/.my.cnf
- name: Create mariadb databases
  mysql_db: name="{{ wp_mysql_db }}" state=present
- name: Create mariadb username and password
  mysql_user:
#    login_user=root
#    login_password=redhat 
    name="{{ wp_mysql_user }}"
    password="{{ wp_mysql_password }}"
    priv="*.*:ALL"

